### ISSUE TITLE
NodeIds in Types

### ISSUE THREAD

**Issue by fpauker** [etm/opcua-smart#3]
When defining two types like:
```ruby
server.add_namespace "https://centurio.work/ur10"

  tt = server.types.add_object_type(:TargetType).tap{ |t|
    t.add_variable :JointPositions
  }
  #causes errors, because both Jointpositions got the same nodeid
  at = server.types.add_object_type(:ActualType).tap{ |t|
    t.add_variable :JointPositions
  }
```

i get an error 
```
AddNodes: Node could not add the new node to the nodestore with error code BadNodeIdExists
```
because both JointPositions nodes got the same Nodeid.

**Comment by etm** [comment]
Thanks for reporting this bug. Nodeids in the types folder are now always numeric and are numbered from 2000 upwards in the order of creation. 

Nodes created with #manifest still automatically have string nodeids representing the hierarchy in the objects folder (no changes here).
