### ISSUE TITLE
Problem (cannot load such file 'lib/opcua/client.so')

### ISSUE THREAD

**Issue by darlandieterich** [etm/opcua-smart#8]
When execute, show this error:
`require_relative': cannot load such file -- /home/user/opcua-smart/lib/opcua/client.so (LoadError)

how fix this error?

https://github.com/etm/opcua-smart/blob/9da1881fffb4c8901b60425428f3cb744c5c2fde/example/client_method.rb#L2

**Comment by etm** [comment]
For the examples i assume that you cloned the repo, and compiled everything with the "rake" command (call it in the top level dir). After that  /home/user/opcua-smart/lib/opcua/client.so should exist. So the commands before trying out the examples are:

cd /home/user/opcua-smart/
rake

Alternative, if you installed the gem correctly: change the require_relative to " require 'opcua/client' "

**Comment by darlandieterich** [comment]
Hi @etm ! I solved it as you commented. I ended up using 'require'

thank you! great work!
