### ISSUE TITLE
How return value in method?

### ISSUE THREAD

**Issue by darlandieterich** [etm/opcua-smart#9]
Hi! The reserved word 'return' is not accepted when call the method, and this aborted.

```
##Server
t.add_method :MethodX,
            inputarg1: OPCUA::TYPES::INT32 do |node, inputarg1|
            p "Argument: #{inputarg1}"
            return inputarg1 + 1
end

##Client
p node.call 1
```

What I do wrong? tnks

**Comment by etm** [comment]
I released (and pushed to git) a version that does it correctly. the return keyword signifies the datatype for the return. Only one return is supported at the moment. As customary in ruby, the last line in the block is the return value, no need to use the return keyword.

```ruby
##Server
t.add_method :MethodX,
            inputarg1: OPCUA::TYPES::INT32,
            return: OPCUA::TYPES::INT32 do |node, inputarg1|
            p "Argument: #{inputarg1}"
            inputarg1 + 1
end

##Client
p node.call 1
```

Discussion: i personally am not a friend of using return values in methods, OPCUA is messy enough as it is. I typically create very simple methods with no return value, and write potential return values into variables in the same folder. This forces me to think more about a good structure. Also it never use long running methods, but instead always rely on conveying method state through some variable in the same folder. But you can of course do whatever you want :-) OPCUA is after all a beloved bloody mess of a thing, that tries to be everything for everybody.

**Comment by darlandieterich** [comment]
Well, I'm one dummy/beginner with OPC-UA. 
I didn’t understand very well how the server collects data from the given equipment, as we don’t have a PLC yet. I am studying the protocol for future deployment of a server in the company. Would you have an example of how this works? this work with folder? how?

very thnks for the push! very useful dude!

**Comment by fpauker** [comment]
In general, to collect data from real world equipment you need some kind of interface to access data from the device and provide it to the opc ua server application. 
Typically this are some vendor specific protocols and then are mapped to opc ua servers.

hopefully this helps you.

**Comment by etm** [comment]
If you want to have a quick gander on some sample servers, e.g. an opcua server for a universal robot 10e, you can join me on discord https://discord.gg/u8Pe49. I will be online until 20:00 Porto Alegre time.

**Comment by darlandieterich** [comment]
@fpauker 
Thanks for reply. what are the main protocols?

**Comment by darlandieterich** [comment]
@etm 
I will do my best to be able to participate. Thanks.
